import type { NextPage } from 'next'
import Head from 'next/head'
import { useCookies } from 'react-cookie';
import { BsFillSunFill, BsFillMoonStarsFill } from 'react-icons/bs';

const Home: NextPage = () => {

  const [cookies, setCookie, removeCookie] = useCookies(['dark']);

  const setDark = () => {
    if (cookies.dark == 'yes') {
      setCookie('dark', 'no')
    } else {
      setCookie('dark', 'yes')
    }
  }

  return (
    <div className={cookies.dark=='yes'?'dark':''}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='dark:bg-gray-600 h-screen'>
        <div className="my-6">
          <button className='bg-sky-600 text-white p-2 px-4 rounded-full hover:opacity-75 hover:text-red-600 dark:bg-gray-800 dark:text-white' onClick={setDark}>
            {
              cookies.dark !== 'yes' &&
              <BsFillSunFill size={18} />
            }
            {
              cookies.dark == 'yes' &&
              <BsFillMoonStarsFill size={18} />
            }
          </button>
        </div>
      </div>
    </div>
  )
}

export default Home
